name: build
on:
  push:
    branches:
      - main
jobs:
  build-wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install wasm-pack
        run: cargo install wasm-pack
      - name: Build wasm
        run: wasm-pack build --target web
      - uses: actions/upload-artifact@v4
        with:
          name: wasm
          path: pkg
          retention-days: 1
          overwrite: true
  build-js:
    runs-on: ubuntu-latest
    needs: build-wasm
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - uses: actions/download-artifact@v4
        with:
          name: wasm
          path: pkg
      - name: Build
        run: npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: js
          path: public/bundle.min.js
          retention-days: 1
          overwrite: true
  deploy:
    runs-on: ubuntu-latest
    needs: [build-wasm, build-js]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v4
        with:
          name: js
          path: public
      - uses: actions/download-artifact@v4
        with:
          name: wasm
          path: tmp
      - run: mv tmp/passphoto_bg.wasm public/
      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: deploy
          FOLDER: public
          SKIP_EMPTY_COMMITS: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}